       @extends('layout.layout')

       @section('content')
       <h1>Terms</h1>
       <div>
           Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis minus modi laborum! Odio animi placeat vel tenetur suscipit cumque error ipsum obcaecati doloribus ipsam, aperiam provident quibusdam eligendi, sequi adipisci.
           Corrupti obcaecati, nemo officiis illum pariatur, voluptatem maiores minus, ab quidem veniam praesentium esse distinctio! Eos, ratione magnam sequi enim debitis totam incidunt voluptatibus accusantium. Reprehenderit voluptatem nemo consequuntur temporibus!
           Vitae, commodi? Placeat tempore deserunt quaerat accusantium repellendus dicta deleniti laborum eum veniam facere accusamus doloribus sit eaque adipisci, voluptatibus molestias possimus recusandae nemo non, ea, nihil amet hic! Sit.
            Deleniti, dignissimos magni vel quas dolor officiis necessitatibus, velit quibusdam illo labore et, itaque quidem accusamus modi! Saepe vitae, iure quod ad natus velit similique ullam adipisci deleniti, voluptatem hic.
            Eum ex sint omnis fugiat in velit expedita exercitationem vitae optio eligendi laudantium sunt nemo placeat sequi ab excepturi, quaerat voluptatem similique aperiam laborum nisi facere cum? Quo, iste repudiandae.
            Alias sit iste ad a, molestias magnam veniam aperiam culpa ea? Nulla recusandae, iure rem dolor esse animi doloribus? Laboriosam minima nam ullam provident unde sint, est perferendis libero veniam?
            Accusantium eaque fugit molestiae ipsam ab! Maxime officiis magni eos officia omnis repellat quas eum cum voluptatum? Rerum, dignissimos nostrum culpa voluptatum explicabo unde labore hic totam quaerat autem? Ratione.
            Iure, velit incidunt cumque officia voluptatum corrupti minima quaerat laborum similique non dolore molestiae consectetur quas itaque, earum ipsam omnis? Dolores, nobis autem? Harum fugit animi quis voluptate quos exercitationem.
            Distinctio saepe aspernatur debitis voluptatibus ratione. Neque nesciunt aperiam natus quibusdam pariatur vero nostrum deleniti unde, fugit sint officiis modi sapiente repellat debitis voluptatum porro? Voluptate sit dolores laudantium dignissimos.
            Harum dicta nobis mollitia architecto sit amet enim quasi perspiciatis quidem repellat blanditiis dolorum reiciendis expedita quisquam recusandae quibusdam rem excepturi tempora aliquid, tempore, illum nostrum ab ipsam beatae! Provident?
            Modi, ratione perspiciatis delectus hic aliquid cumque dignissimos asperiores tenetur dolorum! Delectus nisi maxime repellendus reiciendis perferendis dolor sit, ut dolorum labore aut, totam quibusdam aperiam, rerum error eos quasi?
            Minus est, suscipit modi nostrum ducimus quia corrupti id necessitatibus. Numquam sapiente culpa corrupti expedita voluptate dolor fugiat iure saepe. Dolore quam architecto nesciunt possimus? Nesciunt quo quam modi ratione.
            Rem illo eius saepe fugit? Reprehenderit iste repudiandae molestias. Doloremque, debitis sequi. Nam tempora consectetur fugiat blanditiis, magni adipisci ab natus beatae amet minima sapiente temporibus? Iusto, impedit provident! Reiciendis!
            Sit doloremque mollitia eum fugit illum aut corrupti ducimus eos hic rerum unde sequi tempora incidunt necessitatibus nam quam veniam, minus ullam facilis illo sint culpa. Dignissimos repellat dolorum necessitatibus?
            Enim voluptate vero asperiores mollitia aliquid, corporis voluptates sunt? Sequi repellat, veritatis velit ducimus explicabo, perferendis provident in corrupti, quisquam minus accusantium quasi vel? Quos minus rem veritatis tempora natus?
            Quasi beatae commodi illum sapiente maxime similique quia repudiandae, ad sunt maiores suscipit. Voluptatum voluptatem nihil magnam libero ipsam tempore vel explicabo. Debitis, aperiam corporis quasi harum in voluptas laudantium!
            Ipsa sapiente commodi voluptatem labore eaque dignissimos qui nam consectetur deserunt veniam soluta, assumenda ratione quasi nulla maxime recusandae minus nostrum temporibus reiciendis consequuntur pariatur, velit autem. Nisi, minima eum.
            Consequuntur quis repudiandae incidunt ab obcaecati necessitatibus molestias perferendis corporis adipisci fugiat alias voluptate debitis reprehenderit aperiam tempora laudantium explicabo repellat voluptatum distinctio, quisquam ipsa unde? Maiores neque impedit ipsam.
            Impedit, explicabo non molestias quas accusamus consectetur. Laborum nemo pariatur, reprehenderit non dolor voluptatem inventore aliquid praesentium ut corrupti quasi? Animi amet, nobis temporibus nulla exercitationem iste maiores laudantium possimus.
            Adipisci similique illo dolores explicabo deleniti accusamus veritatis molestiae modi tempora quae eveniet, et eum unde quia id! Alias ut cum vitae error, impedit consectetur laudantium saepe assumenda nobis explicabo!
            Vel asperiores temporibus tempora ex accusamus, perferendis at inventore sunt ipsa mollitia impedit aliquid cupiditate iste, consequuntur reiciendis perspiciatis aut quibusdam explicabo voluptatum rerum iusto quis, iure numquam reprehenderit. Reiciendis.
            Tempore assumenda rerum, dolor magnam tenetur dolorem unde iste id eius nesciunt similique deserunt cum harum doloremque ut quasi delectus nam itaque molestias nemo odit labore nisi. Ut, quia tenetur.
            Fugiat repudiandae officia eum modi soluta repellendus nulla consequuntur voluptas libero? Fugiat dolorum, quo eaque ducimus harum alias possimus voluptate ea, impedit reprehenderit consequatur repellendus libero ab ipsam voluptas expedita?
            Explicabo quos nemo autem minus optio soluta harum dicta id tempore veritatis deserunt veniam culpa enim maxime, ullam eligendi asperiores eveniet temporibus necessitatibus! Numquam aspernatur minima beatae non distinctio vitae.
            Aspernatur consectetur dolorum dignissimos, nesciunt reprehenderit similique voluptates magnam consequuntur est. Quo porro quos saepe architecto ab molestiae quasi necessitatibus animi hic consectetur, nihil quisquam mollitia earum. Praesentium, voluptatem odit.
            Laborum reprehenderit quibusdam, corrupti, suscipit veniam iste maiores dolor exercitationem aspernatur necessitatibus dignissimos perspiciatis, qui voluptatum error dolore quia ullam excepturi aliquam voluptates neque. Repellat ea obcaecati nemo repellendus totam?
            Aspernatur accusantium veritatis animi blanditiis accusamus quae, praesentium et dignissimos voluptatem est nisi! Laboriosam illum, dolore nemo vitae optio quisquam sit placeat nulla obcaecati aliquam et, ut ab repudiandae porro?
            Blanditiis ea itaque nostrum repellendus iste in laudantium adipisci suscipit totam possimus magnam at assumenda, vel recusandae dolor obcaecati provident optio amet quis voluptatum aliquid minus eum eveniet praesentium! Sequi!
            Eligendi natus excepturi corporis error iusto sequi, exercitationem laboriosam! Iste laborum numquam omnis quasi cupiditate quod debitis! Ab dolores, nobis consectetur tempora iste recusandae unde placeat necessitatibus sunt sint amet!
            Ut necessitatibus earum nulla aperiam eaque, assumenda quidem incidunt, fugiat quam, possimus est velit suscipit. Assumenda exercitationem a ad blanditiis itaque cumque. Soluta architecto aperiam laudantium doloribus animi, excepturi dolorum.
            Soluta, aspernatur deserunt! Earum dignissimos nobis quas quam eos, laboriosam aliquid quo, alias quis tempora quaerat consequuntur nulla corporis. Expedita fugit vero quo temporibus voluptatem. Sunt ut tempora totam et!
            Praesentium commodi est maiores iste repellat laborum nesciunt quidem recusandae? Labore eligendi ipsa animi odio nulla tempora placeat quaerat veritatis soluta assumenda distinctio, iusto ex corrupti qui dicta totam autem.
            Vero quidem aspernatur ipsam, dolore, nam rem sit aliquid recusandae alias perspiciatis dicta ab quaerat, eveniet accusamus suscipit hic officiis soluta delectus ratione earum unde impedit? Vel quae amet voluptas.
            Libero dicta at sequi, ipsam illum tempore iste nemo in vel vitae neque animi, rerum fugiat hic quis sunt perferendis? Consequatur temporibus excepturi exercitationem nesciunt, voluptatem officia cumque voluptatibus voluptates!
            Cupiditate placeat pariatur consectetur fugit perspiciatis explicabo iste. Omnis tempora, officiis, adipisci cumque quae eos excepturi quam dolores eaque praesentium dolorem non nihil hic! Temporibus, eius dolorem! Beatae, labore distinctio!
            Eos aliquid delectus itaque qui at unde nobis officia, assumenda deserunt tempore fuga dolorum illo suscipit, repellendus sequi saepe porro similique numquam blanditiis enim voluptas odit? Harum tempora non voluptatem!
            Libero exercitationem numquam esse, corrupti assumenda sit, consequatur neque, nihil aperiam nobis quisquam. Nemo cumque quia aspernatur iure. Veniam animi ullam vitae commodi adipisci itaque dolorem a voluptatum magni vel.
            Praesentium laudantium rem aliquam, quaerat magnam consectetur dolorem velit id vel quasi hic dignissimos impedit minima aspernatur animi nam perspiciatis modi mollitia labore voluptas nemo dolore officia! Quia, assumenda ducimus.
            Totam beatae illo vitae est! Labore a libero delectus molestiae modi blanditiis veritatis, ullam repellendus quos soluta nemo deleniti nobis sequi autem tempore minus id ad et voluptatem? Nihil, delectus!
            Ratione consequatur natus, cum exercitationem dolor sed aperiam ab labore modi, dolorem vel rerum harum velit corrupti enim inventore. Praesentium quis perspiciatis ducimus, provident aperiam odit possimus recusandae mollitia? Saepe!
        </div>
        @endsection